var TEXT_LOSE         = "GAME OVER";
var TEXT_WIN          = "CONGRATULATIONS!!!";
var TEXT_SCORE        = "SCORE";
var TEXT_PLAY         = "PLAY";
var TEXT_RESTART      = "RESTART";
var TEXT_EXIT         = "EXIT";
var TEXT_GAMEOVER     = "GAME OVER";
var TEXT_COMBO        = "COMBO";
var TEXT_HELP         = "CATCH THE STUFF AND AVOID THE BOMBS!";
var TEXT_HELP_MOBILE  = "CATCH THE STUFF AND AVOID THE BOMBS!!";
var TEXT_CREDITS_DEVELOPED = "DEVELOPED BY TRADE";
var TEXT_PRELOADER_CONTINUE = "START";

var TEXT_SHARE_IMAGE = "200x200.jpg";
var TEXT_SHARE_TITLE = "Congratulations!";
var TEXT_SHARE_MSG1 = "You collected <strong>";
var TEXT_SHARE_MSG2 = " points</strong>!<br><br>Share your score with your friends!";
var TEXT_SHARE_SHARE1 = "My score is ";
var TEXT_SHARE_SHARE2 = " points! Can you do better?";